addons:
  apt:
    packages:
      - python-httplib2
      - python-dev
      - python-lxml
    code_climate:
      repo_token: a95d7fec4b248cdd363b8d7144f975463ad856f63185fdc97e7dce20b70d834d
language: python
sudo: false
cache: pip

python:
- '2.7'

env:
- VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
- VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
- VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"


matrix:
- TESTS="1" ODOO_REPO="odoo/odoo"
- UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/odoo-chile/l10n_cl_vat.git
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
#  - coveralls
